---
title: 'Task 1: Agglomerative hierarchical clustering'
author: "Larissa Neilson"
date: "3/5/2021"
output: html_document
  code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
  )
library(tidyverse)
library(here)
library(janitor)
library(NbClust)
library(cluster)
library(factoextra)
library(dendextend)
library(ggdendro)
```

### Hierarchical clustering by complete linkage

```{r}
# Read in the data
water_chem <- read_csv(here("data", "sbc_lter_registered_stream_chemistry.csv")) %>% 
  clean_names()

# Convert -999.0 values to NA
dropna_chem <- water_chem %>% 
  na_if(-999.0)

# Wrangle to have a single summary row per site
site_chem <- dropna_chem %>%
  select(-timestamp_local) %>%  
  pivot_longer(!site_code, names_to = "parameter", values_to = "value") %>%
  group_by(site_code, parameter) %>% 
  summarize(parameter_mean = mean(value, na.rm = TRUE)) %>%
  pivot_wider(names_from = "parameter", values_from = "parameter_mean")
```







#### Data citation

Santa Barbara Coastal LTER and J. Melack. 2019. SBC LTER: Land: Stream chemistry in the Santa Barbara Coastal drainage area, ongoing since 2000 ver 16. Environmental Data Initiative. https://doi.org/10.6073/pasta/67a558a24ceed9a0a5bf5e46ab841174. 
